### ISSUE TITLE
Where is mainnetv2 snapshot file？

### ISSUE THREAD

**Issue by orange723** [mantlenetworkio/networks#67]
I running multi full node now it‘s stop sync，block stop the 61171945

Need snapshot and run full node

**Comment by nebojsa-ristovic** [comment]
Hey @orange723, here you can find links for both full and archive snapshots - https://github.com/mantlenetworkio/networks/blob/main/run-node-mainnetv2.md#download-latest-snapshot-from-mantle

**Comment by orange723** [comment]
It's fix thanks
